jpf-nas.native_classpath =\
   ${jpf-nas}/build/libs/jpf-nas.jar;\
   ${jpf-nas}/lib/*.jar

jpf-nas.classpath =\
   ${jpf-nas}/build/libs/jpf-nas-classes.jar;\
   ${jpf-nas}/build/examples

jpf-nas.test_classpath =\
   ${jpf-nas}/build/classes/java/test
